#  servlet:
#    context-path: /api/NothKingSystem
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://146.56.200.9:3308/jbf?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: user
   # username: root
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
  #  password: 123456

  redis:
    host: 146.56.216.173
    password:
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 200
        max-wait: 10000
        max-idle: 50
        min-idle: 5
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  cache:
    type: caffeine
    cache-names:
      - getPersonById
      - name2
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5s

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#
#    druid:
#      db-type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://146.56.200.9:3308/jbf?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
#      username: root
#      password: 123456
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT1FROMDUAL
#      test-on-borrow: false
#      test-on-return: false
#
mybatis:
  type-aliases-package: com.NorthKingSys.jbf.cn.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
#IO密集型应用，线程数为2N+1
thread-pool-factory:
  corePoolSize: 9
  maxPoolSize: 18
  queueCapacity: 100
  keepAliveSeconds: 120
logging.level.com.NorthKingSys.jbf.cn.mapper : debug

logging:
  level:
    com.jbf.jbfboot.Dao: DEBUG
#配置redis
#  spring.redis.host=localhost
#  spring.redis.password=
#  spring.redis.port=6379